### ISSUE TITLE
MultilipleImageChoiceGame fails to vet consequent inputs

### ISSUE THREAD

**Issue by basic-ohjelmoia** [luupeli/luupeli#11]
MultilipleImageChoiceGame (and possibly also MultilipleChoiceGame) currently fails to vet quick consequent inputs from the user. This causes the game to progress faster than new images/questions get loaded into the ui. In some situations the game can be crashed by doing so (as demonstrated by Timo recently). You can also end up with a progress bar which shows the game progression going past the actual endCounter limit.

The fix shouldn’t be too complicated.

**Comment by hexparvi** [comment]
Should be fixed in 0b7e56f27c4e533146a2e48ab2f6a8fa6a582f81.
